[project]
name = "attrib"
version = "0.0.0"
requires-python = ">=3.11"
dependencies = [
    "numpy",
    "pandas",
    "scipy",
    "statsmodels",
    "lxml",
    "requests",
    "yfinance",
    "matplotlib",
    "reportlab",
    "pyarrow",
    "pc @ git+https://github.com/uty101/Constrained-Portfolio-Optimiser@88e865d8202023cd495dd9866c49e6adbc9f4654",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-socket",
    "pypdf",
]
